#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin

MARIADB_ROOT_PASSWORD = data.get("MARIADB_ROOT_PASSWORD", "Xibosignage@1234")
MARIADB_DATABASE = data.get("MARIADB_DATABASE", "xibosignage")
MARIADB_USER = data.get("MARIADB_USER", "xibosignage")
MARIADB_PASSWORD = data.get("MARIADB_PASSWORD", "Xibosignage@1234")
# Maria db variables
mariadb = {
    "MYSQL_ROOT_PASSWORD": MARIADB_ROOT_PASSWORD,
    "MYSQL_DATABASE": MARIADB_DATABASE,
    "MYSQL_USER": MARIADB_USER,
    "MYSQL_PASSWORD": MARIADB_PASSWORD,
}
agent.write_envfile("database.env", mariadb)

#agent.dump_env()
